data_name=hotpotqa_p1

export CUDA_VISIBLE_DEVICES=0,1,2,3
export DATA_DIR=${DATA_DIR:-data/${data_name}}

WAND_PROJECT="Search-P1"
SELF_CONSISTENCY_WEIGHT=${SELF_CONSISTENCY_WEIGHT:-0}
REFERENCE_ALIGNMENT_WEIGHT=${REFERENCE_ALIGNMENT_WEIGHT:-0.3}

export BASE_MODEL='models/Qwen2.5-3B-Instruct'
# export BASE_MODEL='checkpoints/nq_hotpotqa_p1-search-p1-sft-qwen2.5-3b-it-format/global_step_156'
export EXPERIMENT_NAME=${EXPERIMENT_NAME:-${data_name}-grpo-qwen2.5-3b-v22-b}

export VLLM_ATTENTION_BACKEND=XFORMERS # vllm + qwen2-7b with flash_attn has some issues

PYTHONUNBUFFERED=1 python3 -m verl.trainer.main_ppo_format \
    data.train_files=$DATA_DIR/train.parquet \
    data.val_files=$DATA_DIR/test.parquet \
    data.train_data_num=38400 \
    data.val_data_num=512 \
    data.train_batch_size=384 \
    data.val_batch_size=256 \
    data.max_prompt_length=4096 \
    data.max_response_length=500 \
    data.max_start_length=2048 \
    data.max_obs_length=800 \
    data.shuffle_train_dataloader=True \
    algorithm.adv_estimator=grpo \
    actor_rollout_ref.model.path=$BASE_MODEL \
    actor_rollout_ref.model.enable_gradient_checkpointing=true \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.optim.lr=5e-7 \
    actor_rollout_ref.actor.optim.lr_warmup_steps_ratio=0.285 \
    actor_rollout_ref.actor.use_kl_loss=true \
    actor_rollout_ref.actor.ppo_mini_batch_size=256 \
    actor_rollout_ref.actor.ppo_micro_batch_size=64 \
    actor_rollout_ref.actor.fsdp_config.param_offload=true \
    actor_rollout_ref.actor.fsdp_config.grad_offload=true \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=true \
    actor_rollout_ref.rollout.log_prob_micro_batch_size=128 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.7 \
    actor_rollout_ref.ref.log_prob_micro_batch_size=128 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    algorithm.no_think_rl=false \
    actor_rollout_ref.rollout.n_agent=3 \
    actor_rollout_ref.rollout.temperature=1 \
    actor_rollout_ref.actor.state_masking=true \
    trainer.logger=['swanlab'] \
    +trainer.val_only=false \
    +trainer.val_before_train=false \
    trainer.default_hdfs_dir=null \
    trainer.n_gpus_per_node=4 \
    trainer.nnodes=1 \
    trainer.save_freq=500 \
    trainer.test_freq=500 \
    trainer.project_name=$WAND_PROJECT \
    trainer.experiment_name=$EXPERIMENT_NAME \
    trainer.total_epochs=1 \
    trainer.total_training_steps=30 \
    trainer.default_hdfs_dir=null \
    trainer.default_local_dir=checkpoints/$EXPERIMENT_NAME \
    reward_model.structure_format_score=0.2 \
    reward_model.final_format_score=0.1 \
    reward_model.retrieval_score=0 \
    reward_model.path_match_strategy=intent_lexical \
    reward_model.require_search_for_format=true \
    reward_model.max_plan_steps=4 \
    reward_model.max_reference_steps=4 \
    reward_model.self_consistency_weight=$SELF_CONSISTENCY_WEIGHT \
    reward_model.reference_alignment_weight=$REFERENCE_ALIGNMENT_WEIGHT \
    reward_model.trajectory_dump_path=logs/$EXPERIMENT_NAME.jsonl \
    reward_model.trajectory_dump_limit=120000 \
    max_turns=4 \
    retriever.url="http://127.0.0.1:8000/retrieve" \
    retriever.topk=3 \
    2>&1 | tee logs/$EXPERIMENT_NAME.log
